GET /
SecretKey: 16378346
Host: localhost:8080
###
POST /
Host: localhost:8090
###
POST /login
Host: localhost:8080
Content-Type: application/json

{
    "mobile": "8748874814",
    "name": "mahima",
    "table": 2
}
